language: go

go:
  - 1.16.x

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

script:
  - go clean -testcache
  - go test -v ./...
  - gox -os="linux darwin windows" -arch="amd64" -output="build.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...;


deploy:
  provider: releases
  skip_cleanup: true
  api_key: MDbM443zzelgqPnMfQUgJA
  file:
  - simple-checkout-system.windows.amd64.exe
  - simple-checkout-system.darwin.amd64
  - simple-checkout-system.linux.amd64
  on:
    repo: kennykarnama/checkout-challenge
    tags: true